/**
 * 博客分享功能配置
 */
export const SHARE_CONFIG = {
	/** 水印签名文字 */
	signature: '✨ Written & Generated by Nova with HEART 💗',
	
	/** 是否显示二维码 */
	showQRCode: true,
	
	/** 二维码大小（像素） */
	qrCodeSize: 100,
	
	/** Favicon 路径 */
	faviconPath: '/favicon.png',
	
	/** Favicon 大小（像素） */
	faviconSize: 20,
	
	/** 截图固定宽度（像素）- 确保移动端和桌面端一致 */
	screenshotWidth: 800,

	/** 是否尝试将跨域图片转为 Base64 内联 */
	inlineExternalImages: true,

	/**
	 * 图片代理前缀（可列出多个，会依次尝试）。
	 * 例如 https://images.weserv.nl/?url=
	 */
	imageProxyPrefixes: ['https://images.weserv.nl/?url='],

	/** 单个远程图片的获取超时时间（毫秒） */
	imageFetchTimeoutMs: 8000,

	/** 允许内联的远程图片的最大体积（字节） */
	maxImageBytes: 0,

	allowedDomains: [
		'nova.gal',
		'localhost',
	],
} as const;
